name: miss_minutes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  excel: ^4.0.6
  grouped_list: ^6.0.0
  intl: ^0.19.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  form_builder_validators: ^11.1.2
  flutter_form_builder: ^10.0.1
  equatable: ^2.0.7
  gap: ^3.0.1
  loading_animation_widget: ^1.3.0
  custom_refresh_indicator: ^4.0.1
  flutter_slidable: ^4.0.0
  firebase_core: ^3.12.1
  firebase_database: ^11.3.4
  json_serializable: ^6.9.4
  cloud_firestore: ^5.6.5
  json_annotation: ^4.9.0
  build_runner: ^2.4.15
  dynamic_color: ^1.7.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  file_picker: ^10.0.0

  loomeive:
    git:
      url: git@github.com:eivehub/loomeive.git
  simple_gradient_text: ^1.3.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  sign_button: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/template.xlsx

  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend/static/Lexend-Regular.ttf
