// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcP2Fl8x0X0PcaGf2rSCplmdOyBljb0n8',
    appId: '1:597983428967:web:c3c6306a6edfa294feafc2',
    messagingSenderId: '597983428967',
    projectId: 'tvapp-87586',
    authDomain: 'tvapp-87586.firebaseapp.com',
    storageBucket: 'tvapp-87586.firebasestorage.app',
    measurementId: 'G-DXPG2J1L8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-5b0EZYMEeCfct6-HLefE1GNoMo2cR-g',
    appId: '1:597983428967:android:634664056435788dfeafc2',
    messagingSenderId: '597983428967',
    projectId: 'tvapp-87586',
    storageBucket: 'tvapp-87586.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Vc33pHSxntoaZS1fOn4NlPo0E8RtnaI',
    appId: '1:597983428967:ios:d127c8bec15c05f1feafc2',
    messagingSenderId: '597983428967',
    projectId: 'tvapp-87586',
    storageBucket: 'tvapp-87586.firebasestorage.app',
    iosBundleId: 'com.example.missMinutes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Vc33pHSxntoaZS1fOn4NlPo0E8RtnaI',
    appId: '1:597983428967:ios:d127c8bec15c05f1feafc2',
    messagingSenderId: '597983428967',
    projectId: 'tvapp-87586',
    storageBucket: 'tvapp-87586.firebasestorage.app',
    iosBundleId: 'com.example.missMinutes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcP2Fl8x0X0PcaGf2rSCplmdOyBljb0n8',
    appId: '1:597983428967:web:62be2b818a04b73afeafc2',
    messagingSenderId: '597983428967',
    projectId: 'tvapp-87586',
    authDomain: 'tvapp-87586.firebaseapp.com',
    storageBucket: 'tvapp-87586.firebasestorage.app',
    measurementId: 'G-XVEENBL0J5',
  );
}
